# Generated by Django 5.1.4 on 2025-01-24 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player",
            old_name="pseudo",
            new_name="player",
        ),
    ]
