# Generated by Django 5.1.4 on 2025-02-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="privacy_policy_accepted",
            field=models.BooleanField(default=False),
        ),
    ]
