# Generated by Django 5.1.4 on 2025-02-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pongmatch",
            name="is_played",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tournament",
            name="is_finished",
            field=models.BooleanField(default=False),
        ),
    ]
