# Generated by Django 5.1.4 on 2025-02-14 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="authenticated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tournamentplayer",
            name="authenticated",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="player",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
