# Generated by Django 5.1.4 on 2025-02-21 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pongmatch",
            name="is_played",
        ),
    ]
