# Generated by Django 5.1.4 on 2025-02-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pongset",
            name="duration",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="pongset",
            name="exchanges",
            field=models.IntegerField(default=0),
        ),
    ]
