# Generated by Django 5.1.4 on 2025-01-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="player",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
