# Generated by Django 5.1.4 on 2025-02-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("friend_request", "Friend Request"),
                    ("friend_request_declined", "Friend Request Declined"),
                    ("game_invite", "Game Invite"),
                ],
                max_length=50,
            ),
        ),
    ]
