# Generated by Django 5.1.4 on 2025-01-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_score_player_name_score_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="PongResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user1", models.CharField(default="user1", max_length=100)),
                ("user2", models.CharField(default="user2", max_length=100)),
                ("score1", models.IntegerField(default=0)),
                ("score2", models.IntegerField(default=0)),
                ("winner", models.CharField(blank=True, max_length=100)),
                ("number_of_games", models.IntegerField(default=0)),
                ("points_to_win", models.IntegerField(default=1)),
                ("date_played", models.DateTimeField(auto_now_add=True)),
                ("tournament", models.BooleanField(default=False)),
                ("tournament_name", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="Score",
        ),
    ]
