# Generated by Django 5.1.4 on 2025-02-08 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_customuser_privacy_policy_accepted"),
        ("api", "0002_pongmatch_is_played_tournament_is_finished"),
    ]

    operations = []
