# Generated by Django 5.1.4 on 2025-02-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_player_authenticated_tournamentplayer_authenticated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentplayer",
            name="guest",
            field=models.BooleanField(default=False),
        ),
    ]
