# Generated by Django 5.1.4 on 2025-01-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_pongmatch_user1"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="number_of_games",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="tournament",
            name="points_to_win",
            field=models.IntegerField(default=3),
        ),
    ]
