# Generated by Django 5.1.4 on 2025-01-31 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pongmatch",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.player",
            ),
        ),
    ]
