# Generated by Django 5.1.4 on 2025-02-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_tournamentplayer_guest"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="is_finalized",
            field=models.BooleanField(default=False),
        ),
    ]
