# Generated by Django 5.1.4 on 2025-01-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_pongresult_delete_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pongresult",
            name="user2",
            field=models.CharField(default="Bot_AI", max_length=100),
        ),
    ]
