# Generated by Django 5.1.4 on 2025-01-11 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_pongresult_user2"),
    ]

    operations = [
        migrations.CreateModel(
            name="PongMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user1", models.CharField(default="user1", max_length=100)),
                ("user2", models.CharField(default="Bot_AI", max_length=100)),
                ("sets_to_win", models.IntegerField(default=1)),
                ("points_per_set", models.IntegerField(default=3)),
                ("user1_sets_won", models.IntegerField(default=0)),
                ("user2_sets_won", models.IntegerField(default=0)),
                ("winner", models.CharField(blank=True, max_length=100)),
                ("date_played", models.DateTimeField(auto_now_add=True)),
                ("tournament", models.BooleanField(default=False)),
                ("tournament_name", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PongSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("set_number", models.IntegerField()),
                ("user1_score", models.IntegerField(default=0)),
                ("user2_score", models.IntegerField(default=0)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="api.pongmatch",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="PongResult",
        ),
    ]
