# Generated by Django 5.1.4 on 2025-02-16 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_notification_notification_type"),
        ("api", "0004_tournament_is_finalized"),
    ]

    operations = []
